#!/usr/bin/env bash
#script that displays a list of currently running processes

echo -e "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

ps aux --forest | awk 'NR > 1 {printf "%-10s %-5s %-4s %-5s %-5s %-5s %-8s %-4s %-6s %-6s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11}'
