#!/usr/bin/env bash
# script that displays the PID, along with the process name

pids=$(pgrep -f bash)

# Display PID and process name for each matching process
for pid in $pids; do
    process_name=$(ps -p $pid -o comm=)
    echo "$pid $process_name"
done
